name: Build Stripconfirm actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build plugin
        run: ./gradlew build

      - name: Rename output JAR with commit ID
        run: |
          COMMIT_ID=$(echo "${{ github.sha }}" | cut -c1-7)
          JAR_NAME="StripConfirm-${COMMIT_ID}.jar"
          mv build/libs/*.jar build/libs/${JAR_NAME}
          echo "JAR_NAME=${JAR_NAME}" >> $GITHUB_ENV

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JAR_NAME }}
          path: build/libs/${{ env.JAR_NAME }}
